# Change these first
owner: FHIR-Aggregator # Your GitHub organization or username, where this repository lives
repo: status-monitor # The name of this repository

sites:
  - name: FHIR-Aggregator Landing Page
    url: https://fhir-aggregator.org/
  - name: FHIR Server (cloud)
    url: https://google-fhir.fhir-aggregator.org
    # TODO: Temporarily adding 401 here while we investigate why the Google FHIR service would be returning 401...
    # Example:
    # - Commit: https://github.com/FHIR-Aggregator/status-monitor/commit/ca943a2f03020192c2aa62d4eb20bd16e5740004
    # - Actions: https://github.com/FHIR-Aggregator/status-monitor/actions/runs/18320993111/job/52173722657#step:3:33
    expectedStatusCodes:
      - 200
      - 401

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status-monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "NCPI FHIR-Aggregator Status"
  introMessage: Integrating Fast Healthcare Interoperability Resources (FHIR) from across the NIH Cloud Platform Interoperability Program.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
